# Generated by Django 4.2.7 on 2025-08-21 23:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'This name is too short')])),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('French', 'French'), ('English', 'English')], default='French', max_length=12)),
                ('phrase', models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(1, 'This phrase is too short')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tommy.module')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhraseStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learned', models.BooleanField(default=False)),
                ('views', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tommy.phrase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_phrase_strength', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('French', 'French'), ('English', 'English')], default='French', max_length=12)),
                ('translation', models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(1, 'This phrase is too short')])),
                ('phrase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrase_translation', to='tommy.phrase')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1, 'Choose a name I can call you')])),
                ('xp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='phrase_strength',
            field=models.ManyToManyField(related_name='user_strength', through='tommy.UserPhraseStrength', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='phrase',
            unique_together={('language', 'phrase')},
        ),
    ]
