# Generated by Django 4.2.7 on 2025-01-19 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=39, validators=[django.core.validators.MinLengthValidator(2, 'A word must have at least one letter.')])),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('CN', 'Chinese')], default='EN', max_length=2)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('word_translation', models.ManyToManyField(to='tommy.word')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(5, 'A phrase must have at least two words')])),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('CN', 'Chinese')], default='EN', max_length=2)),
                ('level', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('phrase_translation', models.ManyToManyField(to='tommy.phrase')),
            ],
        ),
    ]
