# Generated by Django 4.2.7 on 2025-02-22 18:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='translations',
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(1, 'This phrase is too short')])),
                ('phrase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phrase_translation', to='tommy.phrase')),
            ],
        ),
    ]
