# Generated by Django 4.2.7 on 2025-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase_translation',
            field=models.ManyToManyField(blank=True, to='tommy.phrase'),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_translation',
            field=models.ManyToManyField(blank=True, to='tommy.word'),
        ),
    ]
