# Generated by Django 4.2.7 on 2025-02-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0002_remove_phrase_translations_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphrasestrength',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
