# Generated by Django 4.2.7 on 2025-01-21 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0002_alter_phrase_phrase_translation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_translation', models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(5, 'A phrase must have at least two words')])),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('CN', 'Chinese')], default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_translation', models.CharField(max_length=39, validators=[django.core.validators.MinLengthValidator(1, 'A word must have at least one letter.')])),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('CN', 'Chinese')], default='EN', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=39, validators=[django.core.validators.MinLengthValidator(1, 'A word must have at least one letter.')]),
        ),
        migrations.AlterField(
            model_name='word',
            name='word_translation',
            field=models.ManyToManyField(to='tommy.wordtranslation'),
        ),
    ]
