# Generated by Django 4.2.7 on 2025-01-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0003_phrasetranslation_wordtranslation_alter_word_word_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrasetranslation',
            old_name='word_translation',
            new_name='phrase_translation',
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase_translation',
            field=models.ManyToManyField(to='tommy.phrasetranslation'),
        ),
    ]
