# Generated by Django 4.2.7 on 2025-03-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0003_userphrasestrength_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphrasestrength',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
