# Generated by Django 4.2.7 on 2025-03-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0004_userphrasestrength_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='learned',
        ),
        migrations.AddField(
            model_name='userphrasestrength',
            name='learned',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserLearnedPhrase',
        ),
    ]
