# Generated by Django 4.2.7 on 2025-01-21 01:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0004_rename_word_translation_phrasetranslation_phrase_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(5, 'A phrase must have at least two words'), django.core.validators.RegexValidator('[a-zA-Z]+\\s+[a-zA-Z]+', 'A phrase must have at least two words')]),
        ),
        migrations.AlterField(
            model_name='phrasetranslation',
            name='phrase_translation',
            field=models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(5, 'A phrase must have at least two words'), django.core.validators.RegexValidator('[a-zA-Z]+\\s+[a-zA-Z]+', 'A phrase must have at least two words')]),
        ),
    ]
