# Generated by Django 4.2.7 on 2025-03-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0005_remove_phrase_learned_userphrasestrength_learned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='language',
            field=models.CharField(choices=[('F', 'French'), ('E', 'English')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('F', 'French'), ('E', 'English')], default='F', max_length=1),
        ),
    ]
