# Generated by Django 4.2.7 on 2025-01-21 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0005_alter_phrase_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(5, 'This phrase is too short'), django.core.validators.RegexValidator('[a-zA-Z]+\\s+[a-zA-Z]+', 'A phrase must have at least two words')]),
        ),
        migrations.AlterField(
            model_name='phrasetranslation',
            name='phrase_translation',
            field=models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(5, 'This phrase is too short'), django.core.validators.RegexValidator('[a-zA-Z]+\\s+[a-zA-Z]+', 'A phrase must have at least two words')]),
        ),
    ]
