# Generated by Django 4.2.7 on 2025-01-28 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0006_alter_phrase_phrase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'This name is too short')])),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(5, 'This phrase is too short')])),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tommy.language')),
            ],
        ),
        migrations.RemoveField(
            model_name='word',
            name='word_translation',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='level',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='phrase_translation',
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(5, 'This phrase is too short')]),
        ),
        migrations.DeleteModel(
            name='PhraseTranslation',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.DeleteModel(
            name='WordTranslation',
        ),
        migrations.AddField(
            model_name='phrase',
            name='translations',
            field=models.ManyToManyField(to='tommy.translation'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tommy.language'),
        ),
    ]
