# Generated by Django 4.2.7 on 2025-03-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0006_phrase_language_translation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='language',
            field=models.CharField(choices=[('French', 'French'), ('English', 'English')], default='French', max_length=12),
        ),
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(choices=[('French', 'French'), ('English', 'English')], default='French', max_length=12),
        ),
    ]
