# Generated by Django 4.2.7 on 2025-01-28 20:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tommy', '0007_language_translation_remove_word_word_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French')], max_length=2, unique=True, validators=[django.core.validators.MinLengthValidator(3, 'This name is too short')]),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1, 'Add your name')])),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('learning', models.ForeignKey(default='FR', on_delete=django.db.models.deletion.SET_DEFAULT, to='tommy.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
