# Generated by Django 4.2.7 on 2025-03-06 02:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0007_alter_phrase_language_alter_translation_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(5, 'This name is two short')])),
            ],
        ),
        migrations.AddField(
            model_name='phrase',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tommy.module'),
        ),
    ]
