# Generated by Django 4.2.7 on 2025-03-06 02:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0008_module_phrase_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(5, 'This name is too short')]),
        ),
    ]
