# Generated by Django 4.2.7 on 2025-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0009_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphrasestrength',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
