# Generated by Django 4.2.7 on 2025-01-31 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0010_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French')], max_length=2, unique=True),
        ),
    ]
