# Generated by Django 4.2.7 on 2025-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0010_userphrasestrength_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='phrases',
            field=models.ManyToManyField(related_name='module_phrase', to='tommy.phrase'),
        ),
    ]
