# Generated by Django 4.2.7 on 2025-01-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0011_alter_language_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French')], max_length=20, unique=True),
        ),
    ]
