# Generated by Django 4.2.7 on 2025-03-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0011_module_phrases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='phrases',
        ),
    ]
