# Generated by Django 4.2.7 on 2025-01-31 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0012_alter_language_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='learning',
            field=models.ForeignKey(default='French', on_delete=django.db.models.deletion.SET_DEFAULT, to='tommy.language'),
        ),
    ]
