# Generated by Django 4.2.7 on 2025-05-30 23:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0012_remove_module_phrases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=24, validators=[django.core.validators.MinLengthValidator(3, 'This name is too short')]),
        ),
    ]
