# Generated by Django 4.2.7 on 2025-01-31 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0013_alter_profile_learning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(choices=[('Anglais', 'Anglais'), ('French', 'French')], max_length=20, unique=True),
        ),
    ]
