# Generated by Django 4.2.7 on 2025-02-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0014_alter_language_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
