# Generated by Django 4.2.7 on 2025-02-11 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0016_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='User', max_length=25, validators=[django.core.validators.MinLengthValidator(1, 'Choose a name I can call you')]),
        ),
    ]
