# Generated by Django 4.2.7 on 2025-02-11 01:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0017_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1, 'Choose a name I can call you')]),
        ),
    ]
