# Generated by Django 4.2.7 on 2025-02-15 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tommy', '0018_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(1, 'This phrase is too short')]),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation',
            field=models.CharField(max_length=248, validators=[django.core.validators.MinLengthValidator(1, 'This phrase is too short')]),
        ),
    ]
