# Generated by Django 4.2.7 on 2025-02-15 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tommy', '0019_alter_phrase_phrase_alter_translation_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
        migrations.AddField(
            model_name='phrase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phrase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PhraseStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=1)),
                ('user_phrase_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tommy.phrase')),
            ],
            options={
                'unique_together': {('learner', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='LearnedPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase_learned', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tommy.phrase')),
            ],
            options={
                'unique_together': {('learner', 'phrase')},
            },
        ),
        migrations.AddField(
            model_name='phrase',
            name='learned',
            field=models.ManyToManyField(related_name='phrases_learned', through='tommy.LearnedPhrase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phrase',
            name='phrase_strength',
            field=models.ManyToManyField(related_name='phrases_strength', through='tommy.PhraseStrength', to=settings.AUTH_USER_MODEL),
        ),
    ]
